### ISSUE TITLE
ndk-build fails

### ISSUE THREAD

**Issue by inversebit** [gomezgoiri/CLIPS4Android#3]
When compiling with ndk-build the process fails with the following error:

ClipsAndroid/jni/clips/router.c:140:7: error: format not a string literal and no format arguments [-Werror=format-security]

This error may be associated with the operating system. I'm running Mint16x86_64, in which OS do you run ndk-build gomezgoiri?

I already have a possible patch, will send a pull request shortly.

**Comment by gomezgoiri** [comment]
Great! I ran it on Kubuntu 13.04.
